### ISSUE TITLE
IndexError: index out of range

### ISSUE THREAD

**Issue by Elenedeath** [felipesanches/AnotherWorld_VMTools#11]
Hello got an index out of range when trying to disasm my dos game us

`python banks2resources.py AW/memlist.bin resources` are ok
`python resources2romset.py resources romset` are ok too

```
python AWVM_trace.py romset/ disasm/
disassembling level 0...
        79 cinematic entries.
disassembling level 1...
        570 cinematic entries.
disassembling level 2...
        659 cinematic entries.
disassembling level 3...
        688 cinematic entries.
disassembling level 4...
        890 cinematic entries.
disassembling level 5...
        259 cinematic entries.
disassembling level 6...
        682 cinematic entries.
disassembling level 7...
        108 cinematic entries.
disassembling level 8...
Traceback (most recent call last):
  File "G:\AnotherWorld\AnotherWorld_VMTools\AWVM_trace.py", line 580, in <module>
    trace.run()
  File "G:\AnotherWorld\AnotherWorld_VMTools\exec_trace.py", line 94, in run
    self.disasm[address] = self.disasm_instruction(opcode)
  File "G:\AnotherWorld\AnotherWorld_VMTools\AWVM_trace.py", line 123, in disasm_instruction
    offset = (((opcode & 0x7F) << 8) | self.fetch()) * 2
  File "G:\AnotherWorld\AnotherWorld_VMTools\exec_trace.py", line 220, in fetch
    value = self.rom[self.rombank + self.PC]
IndexError: index out of range
```

**Comment by felipesanches** [comment]
ouch!

I only saw this message now. Sorry.

I will take a closer look at this later this week

**Comment by felipesanches** [comment]
ok. I finally fixed it this morning!

Have fun! And please let us know what you end up doing with the toolchain :-)
